name: Auto CI
on: [push, pull_request]
jobs:
  build:
    name: Auto triggered CI job
    runs-on: ubuntu-latest
    steps:
    - 
      name: Set up Go 1.23.0
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.0
      id: go
    - 
      name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0
    - 
      name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
